[build]
  command = "npm run build"
  publish = "build"
  base = "/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[template.environment]
  REACT_APP_FIREBASE_API_KEY = "Your Firebase API Key"
  REACT_APP_FIREBASE_AUTH_DOMAIN = "Your Firebase Auth Domain"
  REACT_APP_FIREBASE_PROJECT_ID = "Your Firebase Project ID"
  REACT_APP_FIREBASE_STORAGE_BUCKET = "Your Firebase Storage Bucket"
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID = "Your Firebase Messaging Sender ID"
  REACT_APP_FIREBASE_APP_ID = "Your Firebase App ID"